### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by fbrissi** [jgroups-extras/jgroups-aws#132]
Is there any expectation of having a new release from the master in maven repository?

**Comment by belaban** [comment]
Why? AFAIR, there hasn't been any code changes recently

**Comment by fbrissi** [comment]
The PR [130](https://github.com/jgroups-extras/native-s3-ping/pull/130) not in none tag, and the last tag in maven repository is 1.0.0.Final but we already have the tag native-s3-ping-2.0.0.Final

**Comment by rhusar** [comment]
@fbrissi OK I ll look into this as I will be fixing this repo (this week).

**Comment by rhusar** [comment]
There are changes since last tag, namely new properties around ACL path_style_access_enabled & acl_grant_bucket_owner_full_control

Here's full diff: https://github.com/jgroups-extras/native-s3-ping/compare/native-s3-ping-2.0.0.Final...main

I will release it later today since 2.0.0.Final was never released in maven anyway https://repository.jboss.org/org/jgroups/aws/s3/native-s3-ping/ and no projects upgrading to jgroups 5.x can pick it up anwyay.

**Comment by belaban** [comment]
Sounds good!

**Comment by rhusar** [comment]
@fbrissi The release is out. Make sure to use the right GAV as per https://github.com/jgroups-extras/jgroups-aws#artifact
